### ISSUE TITLE
could not locate the bindings file

### ISSUE THREAD

**Issue by zhoufenfens** [shakyShane/html-injector#11]
hi,the console said 
> Could not locate the bindings file ,Tried
> \node_modules\bs-html-injector\node_modules\jsdom\node_modules\contextify\build\contextify.node
> \node_modules\bs-html-injector\node_modules\jsdom\node_modules\contextify\build\Debug\contextify.node

when i use the plugins,the error info came from the bindings.js.how strange

**Comment by henryoliver** [comment]
What is your NPM and NODE versions? Can you trie to install again and paste here the log message?
>npm install bs-html-injector

**Comment by henryoliver** [comment]
@zhoufenfens please refer to the issue #13, it may solve your problem.

**Comment by shakyShane** [comment]
fixed in bs-html-injector@3.0.0
