### ISSUE TITLE
Dependency error after NodeJS update.

### ISSUE THREAD

**Issue by henryoliver** [shakyShane/html-injector#13]
Hey guys, anyone know when html-injector will update dependencies? I start to get this error since i update node.

I really appreciate any kind of help on that issue:

npm install bs-html-injector --save-dev

> contextify@0.1.14 install /Users/Projects/app/node_modules/contextify
> node-gyp rebuild

14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Projects/app/node_modules/contextify
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

Thanks!

**Comment by heyamykate** [comment]
Exact same thing is happening to me, I've searched high and low for an answer to no avail. :/

**Comment by polarathene** [comment]
@shakyShane I just ran into this myself on Win 8.1x64, Node 4.1.2. Seems to be due to contextify issue with node-gyp.

**Comment by polarathene** [comment]
I've copied over an installed version from node_modules in an older project. `npm install -g npm-check-updates` then `ncu` in the `node_modules/bs-html-injector/` directory. It lists updates, `ncu -u` will update the package.json, `npm install` after. I run my gulp task and html is injecting fine, all seems fine :)

**Comment by henryoliver** [comment]
@polarathene 
What is your Node and NPM version?

**Comment by polarathene** [comment]
@henryoliver Node 4.1.2, NPM 2.14.4. Not sure what NPM version I had prior when using Node 0.10 before updating.

**Comment by henryoliver** [comment]
Which bs-html-injector version is working for you? My npm is 3.3.4.



—

**Comment by polarathene** [comment]
@henryoliver Uhh none will work for me via `npm install`, hence why I came here to chime in :) I had a prior project with the package installed in `node_modules` so I coped that over with the instructions I posted above.

You can find more information [over here](http://stackoverflow.com/questions/33012192/npm-package-has-outdated-dependency-is-there-a-way-to-alter-its-version/33035623#33035623). I didn't need to pull a copy from github, but you should be able to copy the repo and place it in `node_modules/bs-html-injector/`. 

Once you've done that update the dependencies like I explained in my earlier post above. Afterwards you should have a working bs-html-injector package :) no easier way beyond @shakyShane updating his package.json or someone making a fork.

**Comment by henryoliver** [comment]
@heyamykate, @polarathene, @xkxx, @shakyShane, @waffle-iron 

Hey guys, follow the final solution

1 - Download the package direct from its repositirie: https://github.com/shakyShane/html-injector/
2 - Copy to your node_modules
3 - Install this package globally npm install -g npm-check-updates.
4 - Go inside the folder node_modules/bs-html-injector/
5 - Type _ncu_ command, you will see the dependecies to update then type ncu -u and npm install to update all.

That's it. Thank you @polarathene for the solution!

**Comment by zhoufenfens** [comment]
@henryoliver thank you very much,i will try tomorrow in my office, it is 00:12 in China,

**Comment by polarathene** [comment]
@henryoliver keep the issue open for @shakyShane . The solution works but @shakyShane still needs to update the dependencies or receive a pull request from an updated fork so we and everyone else don't have to fix it ourselves. If you leave the issue open anyone else with the problem will see the instructions you shared.

**Comment by zhoufenfens** [comment]
@henryoliver thank you,this method solve my problem.

**Comment by shakyShane** [comment]
@polarathene if you have the solution, please send a PR :)

**Comment by polarathene** [comment]
@shakyShane please accept PR: https://github.com/shakyShane/html-injector/pull/14
