### ISSUE TITLE
TypeError: bs.io.of(...).sockets.map is not a function

### ISSUE THREAD

**Issue by fenixwu** [shakyShane/html-injector#17]
Hello,
<p>Use Webpack to watch *.jade.</p>
<p>Error happens when saving *.jade to active live reload.</p>

Error:

    /home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/bs-html-injector/index.js:220
        var valid = bs.io.of(bs.options.getIn(["socket", "namespace"])).sockets.map(function (client) {
                                                                                ^

    TypeError: bs.io.of(...).sockets.map is not a function
        at requestNew (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/bs-html-injector/index.js:220:81)
        at doNewRequest (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/bs-html-injector/index.js:210:9)
        at EventEmitter.pluginEvent (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/bs-html-injector/index.js:199:9)
        at emitNone (events.js:67:13)
        at EventEmitter.emit (events.js:166:7)
        at module.exports (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/bs-html-injector/index.js:35:24)
        at FSWatcher.<anonymous> (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/server.js:18:3)
        at emitTwo (events.js:87:13)
        at FSWatcher.emit (events.js:172:7)
        at FSWatcher.<anonymous> (/home/newcasino/trunk_mem/fuel/app/views/infe/mcenter/paycompany/node_modules/browser-sync/node_modules/chokidar/index.js:171:15)

Code:

    var bs = require('browser-sync').create();
    var spa = require('browser-sync-spa');
    var htmlInjector = require('bs-html-injector');

    bs.use(spa());
    bs.use(htmlInjector);
    bs.watch('app/*.jade').on('change', function () {
        htmlInjector();
    });

Package:

    "browser-sync": "2.10.1",
    "browser-sync-spa": "1.0.3",
    "bs-html-injector": "3.0.0",

**Comment by joriscolours** [comment]
+1, with Mustache templates setup

        browserSync.use(htmlInjector, {
            files: config.paths.dest.patterns + '**.*.html'
        });

        browserSync.init({
            server: {
                baseDir: config.paths.dest.root
            }
        });

        gulp.watch(config.paths.dest.patterns + '/**/*.html', htmlInjector);

**Comment by Kjaer** [comment]
I started to get same error, Using gulp.
Here is my config.
```javascript
browserSync.init(assets, {
            proxy: 'localhost:51981',
            port: 2000,
            ui: {
              port:2010  
            },
            plugins: [
            {
                module: "bs-html-injector",
                options: {
                    files:["../application.Web/Views/**/*.cshtml"]
                }
            }]
        });
```

```
gulp.task("bs-styles", ["brand"], browserSync.reload);
     
gulp.task("fedev", ["browser-sync"], function () {
      gulp.watch("brand/Styles/app/**/*.scss", ["bs-styles"]);
      gulp.watch("brand/Scripts/app/**/*.js", ["bs-styles"]);
});
```

**Comment by shakyShane** [comment]
@fenixwu which version of `node`?

**Comment by fenixwu** [comment]
I'm using Node 4.2.2.

**Comment by GC-Mark** [comment]
Also started getting this error, although not sure what I changed between it working and not.
`node v0.10.33`

**Comment by GC-Mark** [comment]
Just observed this.

When it doesn't work, the version of `socket.io-client` is `1.4.4`

If I rollback `socket.io-client` to `1.3.7` everything works.

(Haven't tried any other `socket.io-client` versions)

**Comment by Kjaer** [comment]
@GC-Mark how do you rollback socket.io-client?
isn't it node_modules folder? Do you do it manually? or programmatically?

**Comment by GC-Mark** [comment]
Go into your `node_modules` folder and in both the `bs-html-injector` folder and the `browser-sync` folder open the `package.json` and change the `socket.io-client` version number to `1.3.7` (remove any `^` symbols to make sure we get this exact version)

Then, in the `bs-html-injector` folder and the `browser-sync` folder run `npm install`

**Comment by Kjaer** [comment]
@GC-Mark thanks mate.

**Comment by joriscolours** [comment]
That works.

**Comment by Kjaer** [comment]
I've tried at same solution but did'nt work for me. I presume I am using higher version of bs-html-injector.

**Comment by JayBizzle** [comment]
@Kjaer What output do you get if you run `npm list --depth=1 | grep socket`

**Comment by Kjaer** [comment]
@JayBizzle  When I run the command in ``` node_modules/browser-sync``` I've got these

```
$ npm list --depth=1 | grep socket
├─┬ socket.io@1.4.4
│ ├── socket.io-adapter@0.4.0
│ ├── UNMET DEPENDENCY socket.io-client@1.4.4
│ └── socket.io-parser@2.2.6
├─┬ socket.io-client@1.3.7
│ ├── socket.io-parser@2.2.4
npm ERR! missing: graceful-fs@^4.1.2, required by readdirp@2.0.0
npm ERR! missing: chalk@^0.5.1, required by tfunk@3.0.1
npm ERR! missing: graceful-fs@^4.1.2, required by fs-extra@0.26.4
npm ERR! missing: request@2.65.0, required by localtunnel@1.8.0
npm ERR! missing: has-binary@0.1.7, required by socket.io@1.4.4
npm ERR! missing: socket.io-client@1.4.4, required by socket.io@1.4.4
npm ERR! missing: engine.io-parser@1.2.4, required by engine.io@1.6.7
npm ERR! missing: ws@1.0.1, required by engine.io@1.6.7
```

and then I run the command in ```bs-html-injector folder```
I received these:
```
$ npm list --depth=1 | grep socket
│ ├── socket.io@1.4.4
└─┬ socket.io-client@1.3.7
  ├── socket.io-parser@2.2.4
```

**Comment by JayBizzle** [comment]
@Kjaer not quite sure what has gone on there. Perhaps it is becuase you are using `v3.0.0` whereas i'm using `2.0.4`.

What version were you using @joriscolours?

Hopefull @shakyShane can push a more permanent solution soon :pray:

**Comment by joriscolours** [comment]
@JayBizzle "bs-html-injector": "^3.0.0",

**Comment by fenixwu** [comment]
@shakyShane please Help us.

**Comment by shakyShane** [comment]
@fenixwu I will take a look at this today if possible :)

**Comment by rish** [comment]
FWIW here is a shell script I have created to patch this issue till there is an official solution.

```
rm -rf node_modules/bs-html-injector/node_modules
perl -pi -e 's/\"socket.io-client\": \"\^1.1.0\"/\"socket.io-client\": \"1.3.7\"/g' node_modules/bs-html-injector/package.json
(cd node_modules/bs-html-injector && npm install)
```

Which works for `bs-html-injector@2.0.4`.

**Comment by Kjaer** [comment]
I finally find a way through the error.

First I am using 
 - ```browser-sync``` ```2.8.6```
 - ```bs-html-injector``` ```3.0.0```

What I've done this to make it work:
 - first remove ```node_modules``` folder both ```browser-sync``` and ```bs-html-injector``` folder
 - upgrade ```browser-sync``` version on ```bs-html-injector```'s package.json file from ```^2.7.6``` to ```^2.8.2```
 - upgrade ```socket.io-client``` version on ```bs-html-injector```'s package.json file from ```^1.1.0``` to ```1.3.7```
 - Run ```npm install``` for  ```browser-sync``` and ```bs-html-injector``` folder respectively.

**Comment by JamesJosephFinn** [comment]
Yep, same problem here:
`Node 5.3.0`
`browser-sync 2.11.0`
`bs-html-injector 3.0.0`

**Comment by Kjaer** [comment]
@JamesJosephFinn @GC-Mark 's solution could be helpful.
https://github.com/shakyShane/html-injector/issues/17#issuecomment-170532417

**Comment by shakyShane** [comment]
The issue is that socket.io has introduced a breaking change between `1.3.7` & `1.4`.

I've pinned Browsersync socket.io dep to `1.3.7` as a temporary fix and released `browser-sync@2.11.1`

Everyone here should simply nuke their `node_modules` folder and re-install (ensuring you get the latest Browsersync version)

This is semver folks. mostly it works well, but it can all go wrong if just 1 lib does not conform

**Comment by GC-Mark** [comment]
Can confirm, this is now fixed, thanks! :+1:

**Comment by rish** [comment]
Same here, cheers Shane, much appreciated! :+1:

**Comment by shakyShane** [comment]
You are all very much welcome :)

Sorry for the delay!

**Comment by fenixwu** [comment]
Thanks a lot:+1:

**Comment by JamesJosephFinn** [comment]
Yessir, thank you so much for this great tool.
