### ISSUE TITLE
What about Grunt?

### ISSUE THREAD

**Issue by trevordmiller** [shakyShane/html-injector#4]
@shakyShane: I would love to try this out and include it with my BrowserSync setup; I am currently using https://github.com/shakyShane/grunt-browser-sync. However, it looks like this repo doesn't support Grunt yet...is that true? Or is it just missing documentation for Grunt? How can I include the `html-injector` as part of my Grunt BrowserSync task?

Thank you for your amazing work. I love BrowserSync and have converted my co-workers to using it in our default starter kit (built with Yeoman) :)

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/recipes/tree/master/recipes/grunt.html.injection
