### ISSUE TITLE
Is it production-ready ?

### ISSUE THREAD

**Issue by omefire** [shakyShane/html-injector#7]
Hi @shakyShane , I was wondering why this plugin is not made a default plugin in BrowserSync ?
I've tried it and it does work as far as I can tell. 
Is it not production-ready ?

**Comment by shakyShane** [comment]
It's mostly ok, but I would not be confident to call it production ready just yet - I'm using it on many projects myself at the moment and refining as I go along :)

**Comment by stereokai** [comment]
@shakyShane Can it work with single page apps using frameworks like Angular, React, etc?

**Comment by shakyShane** [comment]
Please continue discussion at https://github.com/shakyShane/html-injector/issues/9
